# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x02\n\rWeatherEntity\x12&\n\x04main\x18\x01 \x03(\x0b\x32\x18.WeatherEntity.MainEntry\x12*\n\x07weather\x18\x02 \x03(\x0b\x32\x19.WeatherEntity.SubWeather\x12&\n\x04wind\x18\x03 \x03(\x0b\x32\x18.WeatherEntity.WindEntry\x1ao\n\nSubWeather\x12\x33\n\x05value\x18\x01 \x03(\x0b\x32$.WeatherEntity.SubWeather.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tMainEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tWindEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"7\n\rCapitalEntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lng\x18\x03 \x01(\x02\"\x85\x01\n\x14UpdateCapitalRequest\x12\x1f\n\x07\x63\x61pital\x18\x01 \x01(\x0b\x32\x0e.CapitalEntity\x12\x1f\n\x07weather\x18\x02 \x01(\x0b\x32\x0e.WeatherEntity\x12+\n\x07send_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x0f\n\rEmptyResponse2:\n\x07Weather\x12/\n\x06Update\x12\x15.UpdateCapitalRequest\x1a\x0e.EmptyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _WEATHERENTITY_SUBWEATHER_VALUEENTRY._options = None
  _WEATHERENTITY_SUBWEATHER_VALUEENTRY._serialized_options = b'8\001'
  _WEATHERENTITY_MAINENTRY._options = None
  _WEATHERENTITY_MAINENTRY._serialized_options = b'8\001'
  _WEATHERENTITY_WINDENTRY._options = None
  _WEATHERENTITY_WINDENTRY._serialized_options = b'8\001'
  _globals['_WEATHERENTITY']._serialized_start=51
  _globals['_WEATHERENTITY']._serialized_end=393
  _globals['_WEATHERENTITY_SUBWEATHER']._serialized_start=192
  _globals['_WEATHERENTITY_SUBWEATHER']._serialized_end=303
  _globals['_WEATHERENTITY_SUBWEATHER_VALUEENTRY']._serialized_start=259
  _globals['_WEATHERENTITY_SUBWEATHER_VALUEENTRY']._serialized_end=303
  _globals['_WEATHERENTITY_MAINENTRY']._serialized_start=305
  _globals['_WEATHERENTITY_MAINENTRY']._serialized_end=348
  _globals['_WEATHERENTITY_WINDENTRY']._serialized_start=350
  _globals['_WEATHERENTITY_WINDENTRY']._serialized_end=393
  _globals['_CAPITALENTITY']._serialized_start=395
  _globals['_CAPITALENTITY']._serialized_end=450
  _globals['_UPDATECAPITALREQUEST']._serialized_start=453
  _globals['_UPDATECAPITALREQUEST']._serialized_end=586
  _globals['_EMPTYRESPONSE']._serialized_start=588
  _globals['_EMPTYRESPONSE']._serialized_end=603
  _globals['_WEATHER']._serialized_start=605
  _globals['_WEATHER']._serialized_end=663
# @@protoc_insertion_point(module_scope)
